name: Terraform-Apply

on:
  workflow_dispatch:
  push:
    branches: 
    - main
    paths:
    - 'src/terraform/**'

env:
  TERRAFORM_VERSION: '1.5.7'
  WORKING_DIRECTORY: "./src/terraform"

jobs:

  terraform-apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: setup
      name: Setup `terraform`
      uses: hashicorp/setup-terraform@main
      with:
        version: ${{ env.TERRAFORM_VERSION }}

    - id: apply
      name: Terraform Apply
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ vars.AWS_ACCESS_KEY_ID }}
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        terraform init \
          -backend-config='bucket='$BACKEND_BUCKET_NAME \
          -backend-config='region='$BACKEND_REGION \
          -backend-config="key=gcp-vm-sample"

        terraform apply -auto-approve
